name: Update Predictions
on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8:00 AM UTC

jobs:
  update-predictions:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Update predictions data
      run: |
        cd scripts
        python update-predictions.py
      env:
        PREDICTION_DATA: ${{ secrets.PREDICTION_DATA }}

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update predictions - $(date +'%Y-%m-%d')"
        git push

    - name: Debug - Check secret (remove after testing)
      run: |
        echo "Secret length: ${#PREDICTION_DATA}"
        echo "First 100 chars: ${PREDICTION_DATA:0:100}"
